name: Build and Publish to Github Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            # Make sure the actual branch is checked out when running on pull requests
            ref: ${{ github.head_ref }}
            token: ${{ secrets.PAT_WRITE }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@awo00'
      - name: Install Dependencies
        run: npm ci
      - name: Publish package
        run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
