name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            # Make sure the actual branch is checked out when running on pull requests
            ref: ${{ github.head_ref }}
            token: ${{ secrets.GITHUB_TOKEN }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: tsc --build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PAT }}